# Generated by Django 4.1 on 2022-08-07 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
    ]
