# Generated by Django 4.1 on 2022-08-07 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_parrent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_group',
        ),
        migrations.RemoveField(
            model_name='product',
            name='parrent',
        ),
    ]
